export const lightTheme = {
    COLORS: {
        /* Application */
        primary: '#00d8ff',
        primaryHover: '#00B5D4',
        primaryBackgroundExtraLight: '#00EAFF',
        secondary: '#F06292',
        secondaryHover: '#C55178',
        secondaryBackgroundExtraLight: '#F096BF',
        purple: '#8284FA',
        purpleDark: '#5E60CE',
        background: '#f5f5ff',
        textColor400: '#676e79',
        textColor500: '#336e7b',
        borderColor: '#E2E8F0',
        danger: '#D1493D',
        success: '#2B825C',
        warning: '#eba800',
        info: '#21498a',
        white: '#FFFFFF',
        /* Application Components */
        buttonBackground: '#19827d',
        buttonColor: '#FFFFFF',
        buttonHover: '#65c6bb',
        inputBackground: '#FFFFFF',
        inputBackgroundHover: '#228aa2',
        inputColor: '#5B6776',
        inputBorderColor: '#E2E8F0',
        inputBorderColorFocus: '#65c6bb',
        inputPlaceholderColor: '#79808A',
        tableHeaderBackground: '#e4eaf1',
        tableHeaderBorderColor: '#E2E8F0',
        tableRowHover: '#e4eaf17d',

        /* Layout */
        navbarBackground: '#060b26',
        navbarColor: '#e4f1fe',
        navbarBackgroundHover: '#00d8ff',
        scrollbarThumb: '#F06292',
        scrollbarTrack: '#f5f5ff',
        scrollbarThumbHover: '#F06292',

    },
    FONT_SIZES: {
        sm: '.9rem',
        md: '1rem',
        lg: '1.3rem',
        xl: '1.6rem',
        xxl: '2rem',
        xxxl: '2.5rem',
    },
    VH_SIZES: {
        sm: '10vh',
        md: '15vh',
        lg: '20vh',
        xl: '25vh',
        xxl: '30vh',
    },
    VW_SIZES: {
        sm: '10vw',
        md: '15vw',
        lg: '20vw',
        xl: '25vw',
        xxl: '30vw',
    },
}
